{{- $root := . -}}
{{- $name := include "jitsi-meet.name-jvb" $root -}}
{{- range $index, $nbr := until (.Values.prosody.replicaCount | int) }}
---
{{- $depName := printf "%s-%d" $name $nbr -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $depName | quote }}
  labels:
{{ include "jitsi-meet.labels" $root | indent 4 }}
spec:
  replicas: {{ $root.Values.jvb.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $depName | quote }}
      app.kubernetes.io/instance: {{ $root.Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $depName | quote }}
        app.kubernetes.io/instance: {{ $root.Release.Name }}
    spec:
    {{- with $root.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "jitsi-meet.serviceAccountName" $root }}
      securityContext:
        {{- toYaml $root.Values.jvb.securityContext | nindent 8 }}
      containers:
        - name: {{ $name | quote }}
          image: {{ printf "%s:%s" $root.Values.jvb.image.repository $root.Values.jvb.image.tag | quote }}
          imagePullPolicy: {{ $root.Values.jvb.image.pullPolicy | quote }}
          securityContext:
          {{- with $root.Values.jvb.podSecurityContext }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: XMPP_SERVER
              value: {{ include "jitsi-meet.name-prosody" $root }}
            - name: PROSODY_INSTANCE
              value: {{ printf "%d" $nbr | quote }}
            - name: JVB_PORT
              value: {{ printf "%s%s" "3030" (toString $nbr) | quote }}
            - name: JVB_TCP_PORT
              value: {{ printf "%s%s" "3040" (toString $nbr) | quote }}
            - name: JVB_TCP_MAPPED_PORT
              value: {{ printf "%s%s" "3040" (toString $nbr) | quote }}
            - name: JVB_TCP_HARVESTER_DISABLED
              value: "false"
            {{- with $root.Values.jvb.environment }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with $root.Values.common.environment }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: video
              containerPort: {{ printf "%s%s" "3030" (toString $nbr) | int }}
              protocol: UDP
            - name: video-tcp
              containerPort: {{ printf "%s%s" "3040" (toString $nbr) | int }}
              protocol: TCP
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
            {{- if $root.Values.jvb.extraVolumeMounts }}
              {{- toYaml $root.Values.jvb.extraVolumeMounts | indent 12 }}
            {{- end }}
          resources:
            {{- toYaml $root.Values.jvb.resources | nindent 12 }}
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
        {{- if $root.Values.jvb.extraVolumes }}
          {{- toYaml $root.Values.jvb.extraVolumes | indent 8 }}
        {{- end }}
      {{- with $root.Values.jvb.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with $root.Values.jvb.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $root.Values.jvb.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}